### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nunojesus** [NihinlolaFaj/CourierApp#1]
Hello I read your work and I think this is a great project, I saw that you dont have a license on your project, try to have one because it atrack more contributers for your project.
greetings

**Comment by nunojesus** [comment]
If you want I can contribute with graphic design (logo and other stuff).

**Comment by NihinFaj** [comment]
Hello, thank you for the advice. I have now added a license to my project. I would let you know if I need any help concerning my logo and other stuff
